In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.0


# creating first tensor

In [2]:
scalar=tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [3]:
# checking dimension of tensors


In [4]:
scalar.ndim

0

In [5]:
# creating vector tensor 

In [6]:
vector=tf.constant([2,3,4,5])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [7]:
vector.ndim

1

In [8]:
# creating matrix tensor

In [9]:
matrix=tf.constant([[2.,3.,4.],
                  [5.,6.,7.],
                  [8.,9.,10.]])

In [10]:
matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]], dtype=float32)>

In [11]:
matrix.ndim

2

# how to create a tensor

In [12]:
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                    
                    [[7,8,9],
                    [10,11,12]],

                    [[13,14,15],
                    [16,17,18]]],)

In [13]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

# There are two ways to create tensors are:
1) constant
2) variable

In [14]:
unchangeable_tensor=tf.constant([7,7])
changeable_tensor=tf.Variable([10,7])

In [15]:
unchangeable_tensor,changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 7])>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>)

In [16]:
changeable_tensor[1].assign(0)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10,  0])>

In [17]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  0])>

# creating random tensor

In [18]:
random_tensor=tf.random.Generator.from_seed(7)
random_tensor=random_tensor.normal(shape=(3,2))
random_tensor


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

# changing order of elements in a tensor

In [19]:
# shuffling order of a tensor

In [20]:
tensor_not_shuffled=tf.Variable([[1,2],
                                [3,4],
                                [5,6]])                       

In [21]:
# showimg the unshuffled tensor

In [22]:
tensor_not_shuffled

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [23]:
# shuffling the tensor_not_shuffled

In [24]:
tf.random.set_seed=4
tensor_shuffled=tf.random.shuffle(tensor_not_shuffled,seed=4)
tensor_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]])>

# creating a tensor of :
1) All Ones
2) All Zeroes

In [25]:
ones=tf.ones(shape=(3,4))
ones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [26]:
zeros=tf.zeros(shape=(10,10))
zeros

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

# PASSING NUMPY TO TENSOR

In [27]:
import numpy as np 
np_array=np.arange(1,25,dtype=int)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [28]:
tensor1=tf.Variable(np_array)
tensor1

<tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [29]:
# changing shape of numpy array in tensor

In [30]:
tensor2=tf.constant(np_array,shape=(2,3,4))
tensor2

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

# various attributes in tensor
1) Shape
2) Rank
3) Axis/Dimension
4) size
5) Datatype

In [31]:
attributes_tensor=tf.ones(shape=(2,3,4,5))
attributes_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [32]:
print("shape of tensor:",attributes_tensor.shape)
print("Rank of the tensor:",tensor.ndim)
print("element along first axis:",attributes_tensor.shape[-1])
print("Total number of element in a tensor:",tf.size(attributes_tensor))
print("DataType of a tensor:",attributes_tensor.dtype)

shape of tensor: (2, 3, 4, 5)
Rank of the tensor: 3
element along first axis: 5
Total number of element in a tensor: tf.Tensor(120, shape=(), dtype=int32)
DataType of a tensor: <dtype: 'float32'>


In [33]:
# expanding dimension of a tensor

In [34]:
tens=tf.Variable([[1,2,3,4],
                 [5,6,7,8]])


In [35]:
tens

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [36]:
tf.expand_dims(tens,axis=-1)

<tf.Tensor: shape=(2, 4, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8]]])>

# MANIPULATING TENSOR
1. addition
2. multplication
3. subtractions
4. Division

In [37]:
print(tens)
print("addition in tensor:",tens+10)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>
addition in tensor: tf.Tensor(
[[11 12 13 14]
 [15 16 17 18]], shape=(2, 4), dtype=int32)


In [38]:
print(tens)
print("subtraction in tensor:",tens-10)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>
subtraction in tensor: tf.Tensor(
[[-9 -8 -7 -6]
 [-5 -4 -3 -2]], shape=(2, 4), dtype=int32)


In [39]:
print(tens)
print("multiplication in tensor:",tens*10)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>
multiplication in tensor: tf.Tensor(
[[10 20 30 40]
 [50 60 70 80]], shape=(2, 4), dtype=int32)


In [40]:
print(tens)
print("division in tensor:",tens/10)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>
division in tensor: tf.Tensor(
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]], shape=(2, 4), dtype=float64)


# MATRIX MULTIPLICATION
The matrix multiplication is perform by 2 ways:
1) By direct multiplication ---tf.matmul()
2) By dot-product multiplication----tf.tensordot()

In [41]:
# performing matrix multiplication

In [42]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [43]:
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [44]:
matrix_mult=tf.matmul(a,b)

In [45]:
matrix_mult

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [46]:
import numpy as np

In [47]:
c = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
d = tf.constant([7, 8, 9, 10, 11, 12], shape=[2, 3])
c,d

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>)

In [48]:
d=tf.reshape(d,(3,2))

In [49]:
e=tf.matmul(c,d)
e

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

# TENSOR AGGREGATION
1) abosulte value
2) get the minumum
3) get the maximum
4) get the sum
5) get the mean
6) calculating variance of a tensor


In [52]:
tensor1=tf.constant([-1,-2,3,-4])
tensor1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([-1, -2,  3, -4])>

In [53]:
# fetching absolute value from tensor
tf.abs(tensor1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [56]:
# fetching maximum value from tensor
tf.reduce_max(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [57]:
# fetching minimum value from tensor
tf.reduce_min(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=-4>

In [58]:
# fetching mean value from tensor
tf.reduce_mean(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [60]:
# fetching sum of tensor
tf.reduce_sum(tensor1)

<tf.Tensor: shape=(), dtype=int32, numpy=-4>

# TYPE CASTING

In [75]:
tensor.dtype

tf.int32

In [79]:
# casting its type 
tensor1=tf.cast(tensor1,dtype=tf.float32)
tensor1.dtype

tf.float32

In [81]:
# finding variance of a tensor

In [80]:
tf.math.reduce_variance(tf.cast(tensor1,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=6.5>

# FINDING THE POSITIONAL MAXIMUM AND MINIMUM
1) positional maximum
2) positional manimum
3) Index of positional maximum
4) Index of positional Minimum

In [82]:
tensor1=tf.constant([1,65,54,92,2,6,89,5,24,25,32])
tensor1

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 1, 65, 54, 92,  2,  6, 89,  5, 24, 25, 32])>

In [84]:
# positional maximum
tf.argmax(tensor1)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [85]:
# finding index on our maximum value position
tensor1[tf.argmax(tensor1)]

<tf.Tensor: shape=(), dtype=int32, numpy=92>

In [86]:
# positional minimum
tf.argmin(tensor1)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [87]:
# finding index on our minimum value position
tensor1[tf.argmin(tensor1)]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

# ONE HOT ENCODING

In [96]:
colors=[0,1,2,3] # here we providing index for which we done encoding
#colors could be red,blue,green,black
tf.one_hot(colors,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [98]:
tf.one_hot(colors,depth=4,on_value="kartik",off_value="dhasmana") 
# on_values--diagonal value of a tensor 
# off_values--rest remaining values of a tesnor

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'kartik', b'dhasmana', b'dhasmana', b'dhasmana'],
       [b'dhasmana', b'kartik', b'dhasmana', b'dhasmana'],
       [b'dhasmana', b'dhasmana', b'kartik', b'dhasmana'],
       [b'dhasmana', b'dhasmana', b'dhasmana', b'kartik']], dtype=object)>